version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7-stretch
    steps:
      - checkout
      - restore_cache:
          key: bindir
      - run:
          name: Install extra software
          command: |
            sudo apt-get install lua5.1
            sudo apt-get install luarocks
            sudo luarocks install luafilesystem
            sudo luarocks install lpack
            sudo luarocks install md5
            if [ ! -d bin ]; then
                mkdir bin
                cd bin
                wget https://developer.arm.com/-/media/Files/downloads/gnu-rm/7-2017q4/gcc-arm-none-eabi-7-2017-q4-major-linux.tar.bz2
                tar xvfj gcc-arm-none-eabi-7-2017-q4-major-linux.tar.bz2
            fi
      - save_cache:
          key: bindir
          paths:
            - "bin"
      - run:
          name: Build eLua
          command: PATH=$PATH:$(readlink -f bin/gcc-arm-none-eabi-7-2017-q4-major/bin) lua .circleci/ci_builder.lua
